name: Node.js CI

on:
  push:
    branches: [ 'ci', 'dev' ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'

    - run: npm i
      working-directory: 1-order-service
    - run: npm run build --if-present
      working-directory: 1-order-service
    - run: cat Dockerfile
      working-directory: 1-order-service
