name: Node.js CI

on:
  push:
    branches: ['ci', 'dev']
    tags: ['v*']

jobs:
  Order_Service_Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-order-service

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: cat Dockerfile
